Add shell command.

diff --git a/bin/ovena b/bin/ovena
--- a/bin/ovena
+++ b/bin/ovena
@@ -8,7 +8,8 @@ DBNAME="$<DATABASE_NAME>"
 DBUSER="$<DATABASE_USERNAME>"
 ENV="$<OVENA_CONFIG>/ovena.env"
 alias _docker-compose="docker-compose -f $<OVENA_CONFIG>/docker-compose.yml"
-alias _exec="_docker-compose exec -T \"$<DATABASE_DOCKER_IMAGE>\""
+alias _exec="_docker-compose exec"
+alias _exec_db="_docker-compose exec -T \"$<DATABASE_DOCKER_IMAGE>\""
 
 if [ ! -r "${ENV}" ]; then
     printf "ERROR: cannot read configuration file [%s]\n" "${ENV}"
@@ -45,6 +46,8 @@ Commands:
     stop:       Shutdown the ovena stack (DB, orthanc, proxy).
 
     reload:     Restart only Orthanc service. Use to reload config changes.
+
+    shell:      Launch a bash shell inside the Orthanc container.
 
     logs:       Continuosly print Orthanc service logs.
 
@@ -107,7 +110,8 @@ while :; do
 done
 
 _restore() {
-    if [ ! -r "${file}" ]; then printf "ERROR: No backup file [%s] was found.\n" "${file}" && exit 1; fi
+    # If --file parameter starts with a slash, we are assuming the file is an absolute path and resides on the local file system.
+    # If the file does not start wwith a slash, we assume it's on the smb share.
     _log "Restoring from ${file}"
     BKPFILE="${file}"
     BKPFILE_NAME="$(basename "${BKPFILE}")"
@@ -122,15 +126,17 @@ _restore() {
     _docker-compose up -d "$<DATABASE_DOCKER_IMAGE>" || exit 1
     _log "Waiting for DB to start"
     sleep 5
-    _log "Copying backup inside container"
-    docker cp "${BKPFILE}" "ovena-postgres:${BKPFILE_IN_CONTAINER}" || exit 1
-
+    case "${file}" in /*)
+        if [ ! -r "${file}" ]; then printf "ERROR: No backup file [%s] was found.\n" "${file}" && exit 1; fi
+        _log "Copying backup inside container"
+        docker cp "${BKPFILE}" "ovena-postgres:${BKPFILE_IN_CONTAINER}" || exit 1
+    esac
     # DBUSER and DBNAME are created by default by the docker container
     case ${BKPFILE} in
     *.gz)
         UNCOMPRESSED="/mnt/backup/.backup.sql"
         printf " * Uncompressing backup... " &&
-            printf "zcat %s > %s\n" "${BKPFILE_IN_CONTAINER}" "${UNCOMPRESSED}" | _exec bash
+            printf "zcat %s > %s\n" "${BKPFILE_IN_CONTAINER}" "${UNCOMPRESSED}" | _exec_db bash
         printf "done.\n"
         ;;
     *.sql)
@@ -138,8 +144,8 @@ _restore() {
         ;;
     esac
     _log "Restoring backup" &&
-        _exec /usr/bin/psql -v ON_ERROR_STOP=1 ${USEROPT} --file="${UNCOMPRESSED}" &&
-        _exec rm "${UNCOMPRESSED}" "${BKPFILE_IN_CONTAINER}" &&
+        _exec_db /usr/bin/psql -v ON_ERROR_STOP=1 ${USEROPT} --file="${UNCOMPRESSED}" &&
+        _exec_db rm -f "${UNCOMPRESSED}" "${BKPFILE_IN_CONTAINER}" &&
         _docker-compose up -d &&
         _log "Restore completed."
 }
@@ -161,14 +167,14 @@ _upgrade() {
     _tmpdir="$(mktemp -d)"
     _tarball="$(mktemp)"
     # Download latest ovena package
-    curl -sL "https://api.github.com/repos/open-ortho/ovena/tarball" > "${_tarball}"
+    curl -sL "https://api.github.com/repos/open-ortho/ovena/tarball" >"${_tarball}"
 
     # Unpack and run install script
-    cd "${_tmpdir}" && \
-    tar zxvf "${_tarball}" && \
-    cd ovena && \
-    ./ovena-install.sh && \
-    _log "Upgrade Completed succesfully."
+    cd "${_tmpdir}" &&
+        tar zxvf "${_tarball}" &&
+        cd ovena &&
+        ./ovena-install.sh &&
+        _log "Upgrade Completed succesfully."
 }
 
 _backup() {
@@ -180,13 +186,13 @@ _backup() {
     printf "Backing up to %s... " "${DBDUMPFILE}"
     INPROGRESS="${DBDUMPFILE}.in-progress"
 
-    _exec /usr/bin/pg_dump \
+    _exec_db /usr/bin/pg_dump \
         --no-owner -U "${DBUSER}" "${DBNAME}" --file="${INPROGRESS}" || exit
 
-    _exec mv "${INPROGRESS}" "${DBDUMPFILE}" || exit
+    _exec_db mv "${INPROGRESS}" "${DBDUMPFILE}" || exit
     _log "done."
     printf "Compressing... "
-    _exec gzip "${DBDUMPFILE}" || exit
+    _exec_db gzip "${DBDUMPFILE}" || exit
     _log "done."
 }
 
@@ -206,6 +212,10 @@ reload)
     ;;
 logs)
     _docker-compose logs -f orthanc
+    exit
+    ;;
+shell)
+    _exec orthanc bash
     exit
     ;;
 backup)
