Adding import functionality

diff --git a/bin/ovena b/bin/ovena
--- a/bin/ovena
+++ b/bin/ovena
@@ -6,8 +6,9 @@
 VERSION="0.3.1"
 DBNAME="$<DATABASE_NAME>"
 DBUSER="$<DATABASE_USERNAME>"
-ENV="$<OVENA_CONFIG>/ovena.env"
-alias _docker-compose="docker-compose -f $<OVENA_CONFIG>/docker-compose.yml"
+OVENA_CONFIG="$<OVENA_CONFIG>"
+ENV="${OVENA_CONFIG}/ovena.env"
+alias _docker-compose="docker-compose -f ${OVENA_CONFIG}/docker-compose.yml"
 alias _exec="_docker-compose exec"
 alias _exec_db="_docker-compose exec -T \"$<DATABASE_DOCKER_IMAGE>\""
 
@@ -51,15 +52,18 @@ Commands:
 
     logs:       Continuosly print Orthanc service logs.
 
+    import:     Import DICOM files insided the folder specified in --file 
+                into Orthanc.
+
     backup:     Backup PostgreSQL database to <filename> in CIFS  
-                share defined in $<OVENA_CONFIG>/docker-compose.yml.
+                share defined in %s/docker-compose.yml.
 
     restore:    Restore PostgreSQL database from <filename> in CIFS share
-                defined in $<OVENA_CONFIG>/docker-compose.yml.
+                defined in %s/docker-compose.yml.
 
     upgrade:    Upgrade ovena. Checks if there are new versions and upgrades.
 
-" "${VERSION}"
+" "${VERSION}" "${OVENA_CONFIG}" "${OVENA_CONFIG}"
 }
 
 _log() {
@@ -130,6 +134,7 @@ _restore() {
         if [ ! -r "${file}" ]; then printf "ERROR: No backup file [%s] was found.\n" "${file}" && exit 1; fi
         _log "Copying backup inside container"
         docker cp "${BKPFILE}" "ovena-postgres:${BKPFILE_IN_CONTAINER}" || exit 1
+        ;;
     esac
     # DBUSER and DBNAME are created by default by the docker container
     case ${BKPFILE} in
@@ -196,6 +201,26 @@ _backup() {
     _log "done."
 }
 
+_import() {
+    if [ -z "${file}" ]; then
+        log "ERROR: You must specify an input folder using the --file paramenter"
+        exit 1
+    fi
+    VOLUMI="${file}"
+    LOG="/var/log/ovena_import.log"
+    ORTHANC_IP=$(printf "%s" $ORTHANC_IP | sed 's/://')
+    ORTHANC_PORT="443"
+
+    # Launch a separate import process for every first level folder.
+    for folder in $(find "${VOLUMI}" -type d -maxdepth 1); do
+        DIR=$(basename "${folder}")
+        printf "Launching import of %s..." "${folder}"
+        ./ImportDicomFiles.py "${ORTHANC_IP}" "${ORTHANC_PORT}" "${folder}" "${OVENA_CONFIG}/orthanc/users.json" >>"${LOG}/${DIR}_import.log" &
+        echo "done."
+    done
+
+}
+
 command="${1}"
 case ${command} in
 start)
@@ -228,6 +253,10 @@ restore)
     ;;
 upgrade)
     _upgrade
+    exit
+    ;;
+import)
+    _import
     exit
     ;;
 *)
